/turtlesim2/sim:
  ros__parameters:
    window_title: "TurtleSim2"

/turtlesim3/sim:
  ros__parameters:
    window_title: "TurtleSim3"

/**:
  ros__parameters:
    background_b: 255
    background_g: 86
    background_r: 150